#!/usr/bin/env python3
"""디자인 토큰에서 Kotlin(Compose)·Swift(SwiftUI) 상수 파일을 생성한다.

입력: design/handoff/interactions/tokens.json (모션), client/tools/design-tokens.json (색·모서리·간격)
출력: Android WishlistTokens.kt, iOS WishlistTokens.swift
사용: python3 client/tools/gen_tokens.py [--check]
"""
import json
import os
import sys

MOTION_IN = "design/handoff/interactions/tokens.json"
TOKENS_IN = "client/tools/design-tokens.json"
KOTLIN_OUT = "client/android/src/main/kotlin/app/wishlist/android/designsystem/WishlistTokens.kt"
SWIFT_OUT = "client/ios/Wishlist/DesignSystem/WishlistTokens.swift"

HEADER = "// GENERATED by client/tools/gen_tokens.py — do not edit\n"

THEME_FIELDS = ["background", "card", "sheet", "chip", "iconTile", "sheetField", "photo",
                "line", "text", "textSecondary", "tabBar", "underline", "handle", "onInverse",
                "tabPill", "onTabBar", "onTabPill", "scrimDim"]

# 이름 -> tokens.json 경로. 이름은 두 플랫폼 공통 camelCase.
MOTION_MS = [
    ("sheetOpen", ["motions", "sheet", "open", "duration"]),
    ("sheetClose", ["motions", "sheet", "close", "duration"]),
    ("sheetDragDismissSnapBack", ["motions", "sheet", "dragDismiss", "snapBack", "duration"]),
    ("sheetStepResize", ["motions", "sheet", "stepResize", "duration"]),
    ("scrimIn", ["scrim", "in", "duration"]),
    ("scrimOut", ["scrim", "out", "duration"]),
    ("scrimBlur", ["scrim", "blur"]),
    ("dialogIn", ["motions", "dialog", "in", "duration"]),
    ("dialogOut", ["motions", "dialog", "out", "duration"]),
    ("pushPhotoOpen", ["motions", "pushPhoto", "open", "sharedPhoto", "duration"]),
    ("pushPhotoBack", ["motions", "pushPhoto", "back", "sharedPhoto", "duration"]),
    ("pushSurfaceExpand", ["motions", "pushSurface", "expand", "duration"]),
    ("pushPhotoContent", ["motions", "pushPhoto", "open", "content", "duration"]),
    ("pushPhotoBackContent", ["motions", "pushPhoto", "back", "content", "duration"]),
    ("pushSurfaceLift", ["motions", "pushSurface", "lift", "duration"]),
    ("pushSurfaceContentDelay", ["motions", "pushSurface", "content", "delay"]),
    ("pushSurfaceContent", ["motions", "pushSurface", "content", "duration"]),
    ("pushSurfaceBack", ["motions", "pushSurface", "back", "shrink", "duration"]),
    ("pushSurfaceBackContent", ["motions", "pushSurface", "back", "content", "duration"]),
    ("pushSurfaceSettle", ["motions", "pushSurface", "back", "settle", "duration"]),
    ("tabOutgoing", ["motions", "tab", "outgoing", "duration"]),
    ("tabIncoming", ["motions", "tab", "incoming", "duration"]),
    ("tabIncomingDelay", ["motions", "tab", "incoming", "delay"]),
    ("tabPill", ["motions", "tab", "pill", "duration"]),
    ("tabLabelSwapAt", ["motions", "tab", "labelSwapAt"]),
    ("overflowMenu", ["motions", "overflowMenu", "duration"]),
    ("disclosureArrow", ["motions", "disclosureArrow", "duration"]),
    ("disclosureContent", ["motions", "disclosureContent", "duration"]),
]
MOTION_RATIO = [
    ("sheetDragDismissDistanceRatio", ["motions", "sheet", "dragDismiss", "distanceRatio"]),
    ("sheetDragDismissVelocity", ["motions", "sheet", "dragDismiss", "velocity"]),
    ("interactiveBackCommitProgress", ["motions", "interactiveBack", "commitProgress"]),
    ("pushSurfaceLiftOutset", ["motions", "pushSurface", "lift", "outset"]),
    ("pushSurfaceLiftShadowY", ["motions", "pushSurface", "lift", "shadow", "y"]),
    ("pushSurfaceLiftShadowBlur", ["motions", "pushSurface", "lift", "shadow", "blur"]),
    ("pushSurfaceLiftShadowAlpha", ["motions", "pushSurface", "lift", "shadow", "alpha"]),
]


# --- 1. 입력 -------------------------------------------------------------

def load_json(root, rel):
    with open(os.path.join(root, rel), encoding="utf-8") as f:
        return json.load(f)


def dig(data, path):
    for key in path:
        data = data[key]
    return data


# 두 언어에서 예약어인 곡선 이름
RESERVED = {"throw": "throwAway"}


def camel(kebab):
    head, *rest = kebab.split("-")
    name = head + "".join(p.capitalize() for p in rest)
    return RESERVED.get(name, name)


def num(value):
    return "%g" % value


def hex_int(color):
    return color.lstrip("#").upper()


def vals(section):
    """{name: {value, source}} -> [(name, value)] 순서 유지."""
    return [(k, v["value"]) for k, v in section.items()]


# --- 2. 모델 -------------------------------------------------------------

def build_model(motion, tokens):
    colors = tokens["colors"]
    model = {
        "themes": {t: vals(colors[t]) for t in ("light", "dark")},
        "purpose": vals(tokens["purpose"]["surface"]),
        "purposeBorder": vals(tokens["purpose"]["lightBorder"]),
        "onPurpose": tokens["purpose"]["onPurpose"]["value"],
        "status": {t: [(kind, v["surface"]["value"], v["icon"]["value"])
                       for kind, v in tokens["status"][t].items()] for t in ("light", "dark")},
        "dangerSurface": tokens["danger"]["surface"]["value"],
        "dangerOn": tokens["danger"]["onSurface"]["value"],
        "radius": vals(tokens["radius"]),
        "space": vals(tokens["space"]),
        "curves": [(camel(k), v) for k, v in motion["curves"].items()],
        "motionMs": [(n, dig(motion, p)) for n, p in MOTION_MS],
        "motionRatio": [(n, dig(motion, p)) for n, p in MOTION_RATIO],
    }
    for theme, rows in model["themes"].items():
        if [k for k, _ in rows] != THEME_FIELDS:
            raise ValueError("theme %s fields differ from %s" % (theme, THEME_FIELDS))
    return model


def cap(name):
    return name[0].upper() + name[1:]


# --- 3. Kotlin -----------------------------------------------------------

def kt_color(value):
    return "Color(0xFF%s)" % hex_int(value)


def render_kotlin(m):
    out = [HEADER, "package app.wishlist.android.designsystem\n\n",
           "import androidx.compose.animation.core.CubicBezierEasing\n"
           "import androidx.compose.ui.graphics.Color\n"
           "import androidx.compose.ui.unit.Dp\n"
           "import androidx.compose.ui.unit.dp\n\n"]

    out.append("data class WLColors(\n")
    out.append(",\n".join("    val %s: Color" % f for f in THEME_FIELDS))
    out.append(",\n)\n\n")

    def theme_val(name, obj):
        out.append("val %s = WLColors(\n" % name)
        out.append("".join("    %s = WishlistTokens.%s.%s,\n" % (f, obj, f) for f in THEME_FIELDS))
        out.append(")\n\n")

    theme_val("LightColors", "Light")
    theme_val("DarkColors", "Dark")

    out.append("object WishlistTokens {\n")

    def color_object(title, rows, indent="    "):
        out.append("%sobject %s {\n" % (indent, title))
        for k, v in rows:
            if k == "scrimDim":
                out.append("%s    val scrimDim = Color.Black.copy(alpha = %sf)\n" % (indent, num(v)))
            else:
                out.append("%s    val %s = %s\n" % (indent, k, kt_color(v)))
        out.append("%s}\n\n" % indent)

    color_object("Light", m["themes"]["light"])
    color_object("Dark", m["themes"]["dark"])

    out.append("    object Purpose {\n")
    for k, v in m["purpose"]:
        out.append("        val %s = %s\n" % (k, kt_color(v)))
    out.append("        val onPurpose = %s\n\n" % kt_color(m["onPurpose"]))
    color_object("LightBorder", m["purposeBorder"], "        ")
    out[-1] = "        }\n"
    out.append("    }\n\n")

    out.append("    object Status {\n")
    for i, theme in enumerate(("light", "dark")):
        out.append("        object %s {\n" % cap(theme))
        for kind, surface, icon in m["status"][theme]:
            out.append("            val %sSurface = %s\n" % (kind, kt_color(surface)))
            out.append("            val %sIcon = %s\n" % (kind, kt_color(icon)))
        out.append("        }\n" + ("\n" if i == 0 else ""))
    out.append("    }\n\n")

    out.append("    object Danger {\n        val surface = %s\n        val onSurface = %s\n    }\n\n"
               % (kt_color(m["dangerSurface"]), kt_color(m["dangerOn"])))

    out.append("    object Radius {\n")
    out.append("".join("        val %s: Dp = %d.dp\n" % (k, v) for k, v in m["radius"]))
    out.append("    }\n\n    object Space {\n")
    out.append("".join("        val %s: Dp = %d.dp\n" % (k, v) for k, v in m["space"]))
    out.append("    }\n\n    object Curve {\n")
    out.append("".join("        val %s = CubicBezierEasing(%sf, %sf, %sf, %sf)\n"
                       % ((k,) + tuple(num(x) for x in v)) for k, v in m["curves"]))
    out.append("    }\n\n    object Motion {\n")
    out.append("".join("        const val %s: Int = %d\n" % (k, v) for k, v in m["motionMs"]))
    out.append("".join("        const val %s: Float = %sf\n" % (k, num(v)) for k, v in m["motionRatio"]))
    out.append("    }\n}\n")
    return "".join(out)


# --- 4. Swift ------------------------------------------------------------

def sw_color(value):
    return "Color(wlHex: 0x%s)" % hex_int(value)


def render_swift(m):
    out = [HEADER, "import SwiftUI\n\n",
           "extension Color {\n"
           "    init(wlHex: UInt32) {\n"
           "        self.init(\n"
           "            .sRGB,\n"
           "            red: Double((wlHex >> 16) & 0xFF) / 255,\n"
           "            green: Double((wlHex >> 8) & 0xFF) / 255,\n"
           "            blue: Double(wlHex & 0xFF) / 255,\n"
           "            opacity: 1\n"
           "        )\n"
           "    }\n"
           "}\n\n"]

    out.append("struct WLCurve {\n    let x1: Double\n    let y1: Double\n"
               "    let x2: Double\n    let y2: Double\n\n"
               "    func animation(ms: Int) -> Animation {\n"
               "        .timingCurve(x1, y1, x2, y2, duration: Double(ms) / 1000)\n"
               "    }\n}\n\n")

    out.append("struct WLColors {\n")
    out.append("".join("    let %s: Color\n" % f for f in THEME_FIELDS))
    for name, obj in (("light", "Light"), ("dark", "Dark")):
        out.append("\n    static let %s = WLColors(\n" % name)
        out.append(",\n".join("        %s: WishlistTokens.%s.%s" % (f, obj, f) for f in THEME_FIELDS))
        out.append("\n    )\n")
    out.append("}\n\nenum WishlistTokens {\n")

    def color_enum(title, rows, indent="    "):
        out.append("%senum %s {\n" % (indent, title))
        for k, v in rows:
            if k == "scrimDim":
                out.append("%s    static let scrimDim = Color.black.opacity(%s)\n" % (indent, num(v)))
            else:
                out.append("%s    static let %s = %s\n" % (indent, k, sw_color(v)))
        out.append("%s}\n\n" % indent)

    color_enum("Light", m["themes"]["light"])
    color_enum("Dark", m["themes"]["dark"])

    out.append("    enum Purpose {\n")
    for k, v in m["purpose"]:
        out.append("        static let %s = %s\n" % (k, sw_color(v)))
    out.append("        static let onPurpose = %s\n\n" % sw_color(m["onPurpose"]))
    color_enum("LightBorder", m["purposeBorder"], "        ")
    out[-1] = "        }\n"
    out.append("    }\n\n")

    out.append("    enum Status {\n")
    for i, theme in enumerate(("light", "dark")):
        out.append("        enum %s {\n" % cap(theme))
        for kind, surface, icon in m["status"][theme]:
            out.append("            static let %sSurface = %s\n" % (kind, sw_color(surface)))
            out.append("            static let %sIcon = %s\n" % (kind, sw_color(icon)))
        out.append("        }\n" + ("\n" if i == 0 else ""))
    out.append("    }\n\n")

    out.append("    enum Danger {\n        static let surface = %s\n        static let onSurface = %s\n    }\n\n"
               % (sw_color(m["dangerSurface"]), sw_color(m["dangerOn"])))

    out.append("    enum Radius {\n")
    out.append("".join("        static let %s: CGFloat = %d\n" % (k, v) for k, v in m["radius"]))
    out.append("    }\n\n    enum Space {\n")
    out.append("".join("        static let %s: CGFloat = %d\n" % (k, v) for k, v in m["space"]))
    out.append("    }\n\n    enum Curve {\n")
    out.append("".join("        static let %s = WLCurve(x1: %s, y1: %s, x2: %s, y2: %s)\n"
                       % ((k,) + tuple(num(x) for x in v)) for k, v in m["curves"]))
    out.append("    }\n\n    enum Motion {\n")
    out.append("".join("        static let %s: Int = %d\n" % (k, v) for k, v in m["motionMs"]))
    out.append("".join("        static let %s: Double = %s\n" % (k, num(v)) for k, v in m["motionRatio"]))
    out.append("    }\n}\n")
    return "".join(out)


# --- 5. 쓰기 / 검사 ------------------------------------------------------

def generate(root):
    """{출력 상대 경로: 내용}. 같은 입력이면 항상 같은 바이트."""
    model = build_model(load_json(root, MOTION_IN), load_json(root, TOKENS_IN))
    return {KOTLIN_OUT: render_kotlin(model), SWIFT_OUT: render_swift(model)}


def read(path):
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def main(argv, root=None):
    root = root or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    outputs = generate(root)
    if "--check" in argv:
        stale = [rel for rel, text in outputs.items() if read(os.path.join(root, rel)) != text]
        for rel in stale:
            print("stale: %s (run python3 client/tools/gen_tokens.py)" % rel, file=sys.stderr)
        return 1 if stale else 0
    for rel, text in outputs.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
