import contextlib
import io
import os
import re
import shutil
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import gen_tokens  # noqa: E402

REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PURPOSE_KEYS = ["coral", "mustard", "periwinkle", "cyan", "mint", "pink"]


def purpose_keys(text, pattern):
    block = re.search(r"object Purpose \{(.*?)object LightBorder" if pattern == "kt"
                      else r"enum Purpose \{(.*?)enum LightBorder", text, re.S).group(1)
    regex = r"val (\w+) = Color\(0xFF" if pattern == "kt" else r"static let (\w+) = Color\(wlHex: 0x"
    return [k for k in re.findall(regex, block) if k != "onPurpose"]


class GenTokensTest(unittest.TestCase):
    def test_color_requires_six_digit_rgb(self):
        for color in ("#FFF", "#FFFFFFFF", "123456", "##123456", "#12GG56", "#123456\n", None, 123456):
            with self.subTest(color=color), self.assertRaisesRegex(ValueError, "#RRGGBB"):
                gen_tokens.hex_int(color)

    def test_color_normalizes_valid_rgb(self):
        self.assertEqual(gen_tokens.hex_int("#aB12ef"), "AB12EF")

    @classmethod
    def setUpClass(cls):
        cls.outputs = gen_tokens.generate(REPO)
        cls.kotlin = cls.outputs[gen_tokens.KOTLIN_OUT]
        cls.swift = cls.outputs[gen_tokens.SWIFT_OUT]

    def test_curves_match_motion_tokens(self):
        self.assertIn("CubicBezierEasing(0.2f, 1.25f, 0.4f, 1f)", self.kotlin)
        self.assertIn("WLCurve(x1: 0.2, y1: 1.25, x2: 0.4, y2: 1)", self.swift)

    def test_light_dark_backgrounds(self):
        self.assertIn("Color(0xFFF8F8F8)", self.kotlin)
        self.assertIn("Color(0xFF1D1D1D)", self.kotlin)
        self.assertIn("0xF8F8F8", self.swift)
        self.assertIn("0x1D1D1D", self.swift)

    def test_purpose_keys_order(self):
        self.assertEqual(purpose_keys(self.kotlin, "kt"), PURPOSE_KEYS)
        self.assertEqual(purpose_keys(self.swift, "swift"), PURPOSE_KEYS)

    def test_generation_is_deterministic(self):
        again = gen_tokens.generate(REPO)
        for path, text in self.outputs.items():
            self.assertEqual(text.encode("utf-8"), again[path].encode("utf-8"))

    def test_generated_header(self):
        for text in self.outputs.values():
            self.assertTrue(text.startswith("// GENERATED by client/tools/gen_tokens.py"))

    def test_check_mode_detects_stale(self):
        root = tempfile.mkdtemp()
        try:
            for rel in (gen_tokens.MOTION_IN, gen_tokens.TOKENS_IN):
                dst = os.path.join(root, rel)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy(os.path.join(REPO, rel), dst)
            self.assertEqual(gen_tokens.main([], root=root), 0)
            self.assertEqual(gen_tokens.main(["--check"], root=root), 0)
            target = os.path.join(root, gen_tokens.KOTLIN_OUT)
            with open(target, "r+", encoding="utf-8") as f:
                text = f.read()
                f.seek(0)
                f.write(text.replace("0xFFF8F8F8", "0xFFF8F8F9", 1))
                f.truncate()
            with contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(gen_tokens.main(["--check"], root=root), 1)
        finally:
            shutil.rmtree(root)


if __name__ == "__main__":
    unittest.main()
