// GENERATED by client/tools/gen_tokens.py — do not edit
package app.wishlist.android.designsystem

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class WLColors(
    val background: Color,
    val card: Color,
    val sheet: Color,
    val chip: Color,
    val iconTile: Color,
    val sheetField: Color,
    val photo: Color,
    val line: Color,
    val text: Color,
    val textSecondary: Color,
    val tabBar: Color,
    val underline: Color,
    val handle: Color,
    val onInverse: Color,
    val tabPill: Color,
    val onTabBar: Color,
    val onTabPill: Color,
    val scrimDim: Color,
)

val LightColors = WLColors(
    background = WishlistTokens.Light.background,
    card = WishlistTokens.Light.card,
    sheet = WishlistTokens.Light.sheet,
    chip = WishlistTokens.Light.chip,
    iconTile = WishlistTokens.Light.iconTile,
    sheetField = WishlistTokens.Light.sheetField,
    photo = WishlistTokens.Light.photo,
    line = WishlistTokens.Light.line,
    text = WishlistTokens.Light.text,
    textSecondary = WishlistTokens.Light.textSecondary,
    tabBar = WishlistTokens.Light.tabBar,
    underline = WishlistTokens.Light.underline,
    handle = WishlistTokens.Light.handle,
    onInverse = WishlistTokens.Light.onInverse,
    tabPill = WishlistTokens.Light.tabPill,
    onTabBar = WishlistTokens.Light.onTabBar,
    onTabPill = WishlistTokens.Light.onTabPill,
    scrimDim = WishlistTokens.Light.scrimDim,
)

val DarkColors = WLColors(
    background = WishlistTokens.Dark.background,
    card = WishlistTokens.Dark.card,
    sheet = WishlistTokens.Dark.sheet,
    chip = WishlistTokens.Dark.chip,
    iconTile = WishlistTokens.Dark.iconTile,
    sheetField = WishlistTokens.Dark.sheetField,
    photo = WishlistTokens.Dark.photo,
    line = WishlistTokens.Dark.line,
    text = WishlistTokens.Dark.text,
    textSecondary = WishlistTokens.Dark.textSecondary,
    tabBar = WishlistTokens.Dark.tabBar,
    underline = WishlistTokens.Dark.underline,
    handle = WishlistTokens.Dark.handle,
    onInverse = WishlistTokens.Dark.onInverse,
    tabPill = WishlistTokens.Dark.tabPill,
    onTabBar = WishlistTokens.Dark.onTabBar,
    onTabPill = WishlistTokens.Dark.onTabPill,
    scrimDim = WishlistTokens.Dark.scrimDim,
)

object WishlistTokens {
    object Light {
        val background = Color(0xFFF8F8F8)
        val card = Color(0xFFFFFFFF)
        val sheet = Color(0xFFFFFFFF)
        val chip = Color(0xFFFFFFFF)
        val iconTile = Color(0xFFF0F0F0)
        val sheetField = Color(0xFFF0F0F0)
        val photo = Color(0xFFEEEEEE)
        val line = Color(0xFFE2E2E2)
        val text = Color(0xFF1D1D1D)
        val textSecondary = Color(0xFF5E5E5E)
        val tabBar = Color(0xFF1D1D1D)
        val underline = Color(0xFFBDBDBD)
        val handle = Color(0xFFDCDCDC)
        val onInverse = Color(0xFFFFFFFF)
        val tabPill = Color(0xFFFFFFFF)
        val onTabBar = Color(0xFFFFFFFF)
        val onTabPill = Color(0xFF1D1D1D)
        val scrimDim = Color.Black.copy(alpha = 0.24f)
    }

    object Dark {
        val background = Color(0xFF1D1D1D)
        val card = Color(0xFF312F30)
        val sheet = Color(0xFF2A2A2A)
        val chip = Color(0xFF3A3939)
        val iconTile = Color(0xFF1D1D1D)
        val sheetField = Color(0xFF3A3939)
        val photo = Color(0xFF3A3939)
        val line = Color(0xFF3A3939)
        val text = Color(0xFFF4F3F0)
        val textSecondary = Color(0xFFA9A7A2)
        val tabBar = Color(0xFF312F30)
        val underline = Color(0xFF5A5958)
        val handle = Color(0xFF4A4948)
        val onInverse = Color(0xFF1D1D1D)
        val tabPill = Color(0xFFF4F3F0)
        val onTabBar = Color(0xFFF4F3F0)
        val onTabPill = Color(0xFF1D1D1D)
        val scrimDim = Color.Black.copy(alpha = 0.45f)
    }

    object Purpose {
        val coral = Color(0xFFF96857)
        val mustard = Color(0xFFF9CD61)
        val periwinkle = Color(0xFF7477FF)
        val cyan = Color(0xFFBBF3FE)
        val mint = Color(0xFF8ED8B0)
        val pink = Color(0xFFF4A6C6)
        val onPurpose = Color(0xFF1D1D1D)

        object LightBorder {
            val coral = Color(0xFFF84D39)
            val mustard = Color(0xFFB38107)
            val periwinkle = Color(0xFF7477FF)
            val cyan = Color(0xFF0398B5)
            val mint = Color(0xFF369C65)
            val pink = Color(0xFFEA5492)
        }
    }

    object Status {
        object Light {
            val doneSurface = Color(0xFFDCF1E4)
            val doneIcon = Color(0xFF1F7A4D)
            val pendingSurface = Color(0xFFFBEFCB)
            val pendingIcon = Color(0xFF8A6200)
            val offlineSurface = Color(0xFFE2E5FA)
            val offlineIcon = Color(0xFF3E48B8)
            val failedSurface = Color(0xFFFBE1DB)
            val failedIcon = Color(0xFFB03A21)
            val analyzingSurface = Color(0xFFDDF0F5)
            val analyzingIcon = Color(0xFF1C6E82)
        }

        object Dark {
            val doneSurface = Color(0xFF1E3A2B)
            val doneIcon = Color(0xFF7DD3A5)
            val pendingSurface = Color(0xFF3D3216)
            val pendingIcon = Color(0xFFF2C95A)
            val offlineSurface = Color(0xFF262B4D)
            val offlineIcon = Color(0xFFA3ABF5)
            val failedSurface = Color(0xFF432420)
            val failedIcon = Color(0xFFF59A86)
            val analyzingSurface = Color(0xFF1C3740)
            val analyzingIcon = Color(0xFF86D3E6)
        }
    }

    object Danger {
        val surface = Color(0xFFC62828)
        val onSurface = Color(0xFFFFFFFF)
    }

    object Radius {
        val xs: Dp = 10.dp
        val s: Dp = 14.dp
        val m: Dp = 20.dp
        val l: Dp = 28.dp
        val xl: Dp = 36.dp
        val pill: Dp = 999.dp
    }

    object Space {
        val s4: Dp = 4.dp
        val s8: Dp = 8.dp
        val s12: Dp = 12.dp
        val s16: Dp = 16.dp
        val s20: Dp = 20.dp
        val s24: Dp = 24.dp
        val s32: Dp = 32.dp
        val s40: Dp = 40.dp
        val screenMargin: Dp = 20.dp
        val minTouch: Dp = 44.dp
    }

    object Curve {
        val standard = CubicBezierEasing(0.32f, 0.72f, 0f, 1f)
        val springSheet = CubicBezierEasing(0.2f, 1.25f, 0.4f, 1f)
        val accelerate = CubicBezierEasing(0.4f, 0f, 1f, 1f)
        val emphasized = CubicBezierEasing(0.2f, 0f, 0f, 1f)
        val fadeIn = CubicBezierEasing(0f, 0f, 0.2f, 1f)
        val throwAway = CubicBezierEasing(0.5f, 0f, 0.9f, 0.5f)
        val ease = CubicBezierEasing(0.25f, 0.1f, 0.25f, 1f)
        val easeIn = CubicBezierEasing(0.42f, 0f, 1f, 1f)
        val easeOut = CubicBezierEasing(0f, 0f, 0.58f, 1f)
    }

    object Motion {
        const val sheetOpen: Int = 480
        const val sheetClose: Int = 260
        const val sheetDragDismissSnapBack: Int = 300
        const val sheetStepResize: Int = 300
        const val scrimIn: Int = 400
        const val scrimOut: Int = 260
        const val scrimBlur: Int = 12
        const val dialogIn: Int = 200
        const val dialogOut: Int = 150
        const val pushPhotoOpen: Int = 420
        const val pushPhotoBack: Int = 360
        const val pushSurfaceExpand: Int = 420
        const val pushPhotoContent: Int = 420
        const val pushPhotoBackContent: Int = 250
        const val pushSurfaceLift: Int = 80
        const val pushSurfaceContentDelay: Int = 190
        const val pushSurfaceContent: Int = 230
        const val pushSurfaceBack: Int = 360
        const val pushSurfaceBackContent: Int = 180
        const val pushSurfaceSettle: Int = 80
        const val tabOutgoing: Int = 90
        const val tabIncoming: Int = 210
        const val tabIncomingDelay: Int = 90
        const val tabPill: Int = 250
        const val tabLabelSwapAt: Int = 125
        const val overflowMenu: Int = 150
        const val disclosureArrow: Int = 200
        const val disclosureContent: Int = 200
        const val sheetDragDismissDistanceRatio: Float = 0.25f
        const val sheetDragDismissVelocity: Float = 1000f
        const val interactiveBackCommitProgress: Float = 0.5f
        const val pushSurfaceLiftOutset: Float = 3f
        const val pushSurfaceLiftShadowY: Float = 8f
        const val pushSurfaceLiftShadowBlur: Float = 24f
        const val pushSurfaceLiftShadowAlpha: Float = 0.14f
    }
}
