// GENERATED by client/tools/gen_tokens.py — do not edit
import SwiftUI

extension Color {
    init(wlHex: UInt32) {
        self.init(
            .sRGB,
            red: Double((wlHex >> 16) & 0xFF) / 255,
            green: Double((wlHex >> 8) & 0xFF) / 255,
            blue: Double(wlHex & 0xFF) / 255,
            opacity: 1
        )
    }
}

struct WLCurve {
    let x1: Double
    let y1: Double
    let x2: Double
    let y2: Double

    func animation(ms: Int) -> Animation {
        .timingCurve(x1, y1, x2, y2, duration: Double(ms) / 1000)
    }
}

struct WLColors {
    let background: Color
    let card: Color
    let sheet: Color
    let chip: Color
    let iconTile: Color
    let sheetField: Color
    let photo: Color
    let line: Color
    let text: Color
    let textSecondary: Color
    let tabBar: Color
    let underline: Color
    let handle: Color
    let onInverse: Color
    let tabPill: Color
    let onTabBar: Color
    let onTabPill: Color
    let scrimDim: Color

    static let light = WLColors(
        background: WishlistTokens.Light.background,
        card: WishlistTokens.Light.card,
        sheet: WishlistTokens.Light.sheet,
        chip: WishlistTokens.Light.chip,
        iconTile: WishlistTokens.Light.iconTile,
        sheetField: WishlistTokens.Light.sheetField,
        photo: WishlistTokens.Light.photo,
        line: WishlistTokens.Light.line,
        text: WishlistTokens.Light.text,
        textSecondary: WishlistTokens.Light.textSecondary,
        tabBar: WishlistTokens.Light.tabBar,
        underline: WishlistTokens.Light.underline,
        handle: WishlistTokens.Light.handle,
        onInverse: WishlistTokens.Light.onInverse,
        tabPill: WishlistTokens.Light.tabPill,
        onTabBar: WishlistTokens.Light.onTabBar,
        onTabPill: WishlistTokens.Light.onTabPill,
        scrimDim: WishlistTokens.Light.scrimDim
    )

    static let dark = WLColors(
        background: WishlistTokens.Dark.background,
        card: WishlistTokens.Dark.card,
        sheet: WishlistTokens.Dark.sheet,
        chip: WishlistTokens.Dark.chip,
        iconTile: WishlistTokens.Dark.iconTile,
        sheetField: WishlistTokens.Dark.sheetField,
        photo: WishlistTokens.Dark.photo,
        line: WishlistTokens.Dark.line,
        text: WishlistTokens.Dark.text,
        textSecondary: WishlistTokens.Dark.textSecondary,
        tabBar: WishlistTokens.Dark.tabBar,
        underline: WishlistTokens.Dark.underline,
        handle: WishlistTokens.Dark.handle,
        onInverse: WishlistTokens.Dark.onInverse,
        tabPill: WishlistTokens.Dark.tabPill,
        onTabBar: WishlistTokens.Dark.onTabBar,
        onTabPill: WishlistTokens.Dark.onTabPill,
        scrimDim: WishlistTokens.Dark.scrimDim
    )
}

enum WishlistTokens {
    enum Light {
        static let background = Color(wlHex: 0xF8F8F8)
        static let card = Color(wlHex: 0xFFFFFF)
        static let sheet = Color(wlHex: 0xFFFFFF)
        static let chip = Color(wlHex: 0xFFFFFF)
        static let iconTile = Color(wlHex: 0xF0F0F0)
        static let sheetField = Color(wlHex: 0xF0F0F0)
        static let photo = Color(wlHex: 0xEEEEEE)
        static let line = Color(wlHex: 0xE2E2E2)
        static let text = Color(wlHex: 0x1D1D1D)
        static let textSecondary = Color(wlHex: 0x5E5E5E)
        static let tabBar = Color(wlHex: 0x1D1D1D)
        static let underline = Color(wlHex: 0xBDBDBD)
        static let handle = Color(wlHex: 0xDCDCDC)
        static let onInverse = Color(wlHex: 0xFFFFFF)
        static let tabPill = Color(wlHex: 0xFFFFFF)
        static let onTabBar = Color(wlHex: 0xFFFFFF)
        static let onTabPill = Color(wlHex: 0x1D1D1D)
        static let scrimDim = Color.black.opacity(0.24)
    }

    enum Dark {
        static let background = Color(wlHex: 0x1D1D1D)
        static let card = Color(wlHex: 0x312F30)
        static let sheet = Color(wlHex: 0x2A2A2A)
        static let chip = Color(wlHex: 0x3A3939)
        static let iconTile = Color(wlHex: 0x1D1D1D)
        static let sheetField = Color(wlHex: 0x3A3939)
        static let photo = Color(wlHex: 0x3A3939)
        static let line = Color(wlHex: 0x3A3939)
        static let text = Color(wlHex: 0xF4F3F0)
        static let textSecondary = Color(wlHex: 0xA9A7A2)
        static let tabBar = Color(wlHex: 0x312F30)
        static let underline = Color(wlHex: 0x5A5958)
        static let handle = Color(wlHex: 0x4A4948)
        static let onInverse = Color(wlHex: 0x1D1D1D)
        static let tabPill = Color(wlHex: 0xF4F3F0)
        static let onTabBar = Color(wlHex: 0xF4F3F0)
        static let onTabPill = Color(wlHex: 0x1D1D1D)
        static let scrimDim = Color.black.opacity(0.45)
    }

    enum Purpose {
        static let coral = Color(wlHex: 0xF96857)
        static let mustard = Color(wlHex: 0xF9CD61)
        static let periwinkle = Color(wlHex: 0x7477FF)
        static let cyan = Color(wlHex: 0xBBF3FE)
        static let mint = Color(wlHex: 0x8ED8B0)
        static let pink = Color(wlHex: 0xF4A6C6)
        static let onPurpose = Color(wlHex: 0x1D1D1D)

        enum LightBorder {
            static let coral = Color(wlHex: 0xF84D39)
            static let mustard = Color(wlHex: 0xB38107)
            static let periwinkle = Color(wlHex: 0x7477FF)
            static let cyan = Color(wlHex: 0x0398B5)
            static let mint = Color(wlHex: 0x369C65)
            static let pink = Color(wlHex: 0xEA5492)
        }
    }

    enum Status {
        enum Light {
            static let doneSurface = Color(wlHex: 0xDCF1E4)
            static let doneIcon = Color(wlHex: 0x1F7A4D)
            static let pendingSurface = Color(wlHex: 0xFBEFCB)
            static let pendingIcon = Color(wlHex: 0x8A6200)
            static let offlineSurface = Color(wlHex: 0xE2E5FA)
            static let offlineIcon = Color(wlHex: 0x3E48B8)
            static let failedSurface = Color(wlHex: 0xFBE1DB)
            static let failedIcon = Color(wlHex: 0xB03A21)
            static let analyzingSurface = Color(wlHex: 0xDDF0F5)
            static let analyzingIcon = Color(wlHex: 0x1C6E82)
        }

        enum Dark {
            static let doneSurface = Color(wlHex: 0x1E3A2B)
            static let doneIcon = Color(wlHex: 0x7DD3A5)
            static let pendingSurface = Color(wlHex: 0x3D3216)
            static let pendingIcon = Color(wlHex: 0xF2C95A)
            static let offlineSurface = Color(wlHex: 0x262B4D)
            static let offlineIcon = Color(wlHex: 0xA3ABF5)
            static let failedSurface = Color(wlHex: 0x432420)
            static let failedIcon = Color(wlHex: 0xF59A86)
            static let analyzingSurface = Color(wlHex: 0x1C3740)
            static let analyzingIcon = Color(wlHex: 0x86D3E6)
        }
    }

    enum Danger {
        static let surface = Color(wlHex: 0xC62828)
        static let onSurface = Color(wlHex: 0xFFFFFF)
    }

    enum Radius {
        static let xs: CGFloat = 10
        static let s: CGFloat = 14
        static let m: CGFloat = 20
        static let l: CGFloat = 28
        static let xl: CGFloat = 36
        static let pill: CGFloat = 999
    }

    enum Space {
        static let s4: CGFloat = 4
        static let s8: CGFloat = 8
        static let s12: CGFloat = 12
        static let s16: CGFloat = 16
        static let s20: CGFloat = 20
        static let s24: CGFloat = 24
        static let s32: CGFloat = 32
        static let s40: CGFloat = 40
        static let screenMargin: CGFloat = 20
        static let minTouch: CGFloat = 44
    }

    enum Curve {
        static let standard = WLCurve(x1: 0.32, y1: 0.72, x2: 0, y2: 1)
        static let springSheet = WLCurve(x1: 0.2, y1: 1.25, x2: 0.4, y2: 1)
        static let accelerate = WLCurve(x1: 0.4, y1: 0, x2: 1, y2: 1)
        static let emphasized = WLCurve(x1: 0.2, y1: 0, x2: 0, y2: 1)
        static let fadeIn = WLCurve(x1: 0, y1: 0, x2: 0.2, y2: 1)
        static let throwAway = WLCurve(x1: 0.5, y1: 0, x2: 0.9, y2: 0.5)
        static let ease = WLCurve(x1: 0.25, y1: 0.1, x2: 0.25, y2: 1)
        static let easeIn = WLCurve(x1: 0.42, y1: 0, x2: 1, y2: 1)
        static let easeOut = WLCurve(x1: 0, y1: 0, x2: 0.58, y2: 1)
    }

    enum Motion {
        static let sheetOpen: Int = 480
        static let sheetClose: Int = 260
        static let sheetDragDismissSnapBack: Int = 300
        static let sheetStepResize: Int = 300
        static let scrimIn: Int = 400
        static let scrimOut: Int = 260
        static let scrimBlur: Int = 12
        static let dialogIn: Int = 200
        static let dialogOut: Int = 150
        static let pushPhotoOpen: Int = 420
        static let pushPhotoBack: Int = 360
        static let pushSurfaceExpand: Int = 420
        static let pushPhotoContent: Int = 420
        static let pushPhotoBackContent: Int = 250
        static let pushSurfaceLift: Int = 80
        static let pushSurfaceContentDelay: Int = 190
        static let pushSurfaceContent: Int = 230
        static let pushSurfaceBack: Int = 360
        static let pushSurfaceBackContent: Int = 180
        static let pushSurfaceSettle: Int = 80
        static let tabOutgoing: Int = 90
        static let tabIncoming: Int = 210
        static let tabIncomingDelay: Int = 90
        static let tabPill: Int = 250
        static let tabLabelSwapAt: Int = 125
        static let headerCollapseScroll: Int = 300
        static let overflowMenu: Int = 150
        static let disclosureArrow: Int = 200
        static let disclosureContent: Int = 200
        static let sheetDragDismissDistanceRatio: Double = 0.25
        static let sheetDragDismissVelocity: Double = 1000
        static let interactiveBackCommitProgress: Double = 0.5
        static let tabIncomingScale: Double = 0.97
        static let pushSurfaceLiftOutset: Double = 3
        static let pushSurfaceLiftShadowY: Double = 8
        static let pushSurfaceLiftShadowBlur: Double = 24
        static let pushSurfaceLiftShadowAlpha: Double = 0.14
    }
}
