package app.wishlist.shared.model

enum class AnalysisStatus { PROCESSING, READY, PARTIAL, FAILED_RETRYABLE, FAILED_TERMINAL, UNKNOWN }
enum class ReviewStatus { NOT_REQUIRED, PENDING, CONFIRMED, DEFERRED, UNKNOWN }
enum class LifecycleStatus { ACTIVE, ARCHIVED, DELETED }
enum class CategoryMissingReason { EXTRACTION_UNRESOLVED, AI_ABSTAINED, AI_RESPONSE_UNUSABLE, CUSTOM_CATEGORY_DELETED, UNKNOWN }
enum class ValueSource { AI, USER, UNASSIGNED, UNKNOWN }
enum class RequiredAction {
    ANALYSIS_IN_PROGRESS, INFORMATION_COMPLETION, CATEGORY_ASSIGNMENT, CATEGORY_REASSIGNMENT,
    CLASSIFICATION_REVIEW, NONE, UNKNOWN,
}
enum class HomeActionGroup { ANALYSIS_IN_PROGRESS, INFORMATION_COMPLETION, CLASSIFICATION_REVIEW }
enum class ItemAction { EDIT, DELETE, REVIEW, MANUAL_COMPLETE, REANALYZE }
